### ISSUE TITLE
[BE] 팀 구성

### ISSUE THREAD

**Issue by Jiwon-JJW** [kowoohyuk/baseball#1]
- 3팀 씩 나누어 구성한다.
- 팀명 + 팀원 이름으로 구성.

**Comment by Jiwon-JJW** [comment]
- 사랑에 빠진 딸기
  Adela
  eve
  Swing
  Raccoon
  Tami
  Autumn
  Daisy
  ppamppam
  Jenny

- 아몬드봉봉

  Honux

  Beemo
  Rano
  펭도리
  Goody
  Seong
  Dico
  Neis
  Junami

- 애플민트

  Crong

  Sienna
  DD
  Luke
  Q
  Eamon
  Kyle
  json
  young

**Comment by 95degree** [comment]
민트초코 봉봉
roach
Jung
August
노을
Pyro
Bongf
MJ
프레디
jane

레인보우샤베트
Woody
Shion
Coco
Cooper
Tree
Isaac
Robin
hiro
roach

베리베리 스토리베리
K
Bibi
이노
새리
Dong
Kyu
Nas
yeon
Bat
